import type { MetadataRoute } from "next";

import {
  SYSTEM_DESCRIPTION,
  getSystemSettings,
  safeAccentColor,
} from "@/lib/system-settings";

// Render at request time so the manifest reflects the admin-configured brand
// name/accent. Without this, Next caches it statically at build (where there is
// no Cloudflare context, so getSystemSettings falls back to defaults) and the
// installed PWA would be frozen to the default brand. The route reads live
// system settings (a Request-time API), so it must not be statically cached.
export const dynamic = "force-dynamic";

// Dynamic web manifest (served at /manifest.webmanifest) so the installable PWA
// picks up the admin-configured brand name and accent. Brand defaults live in
// lib/system-settings; the square icons are generated by scripts/generate-logo.ts.
export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const settings = await getSystemSettings();
  return {
    name: settings.systemName,
    short_name: settings.systemName,
    description: SYSTEM_DESCRIPTION,
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: safeAccentColor(settings.accentColor),
    icons: [
      { src: "/seeder-icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/seeder-icon-512.png", sizes: "512x512", type: "image/png" },
    ],
  };
}
