/**
 * String builders for the process-manager / ops artifacts generated by the
 * `production (node)` path of `npm run setup`. Kept out of setup.ts to keep the
 * wizard readable. All artifacts assume a SINGLE instance — SQLite is a single
 * writer, so cluster mode / replicas > 1 would corrupt the database.
 */

export type NodeEnv = {
  RUNTIME: string;
  NODE_ENV: string;
  PORT: string;
  HOSTNAME: string;
  BETTER_AUTH_URL: string;
  BETTER_AUTH_SECRET: string;
  VCS_ENCRYPTION_KEY: string;
  OWNER_EMAIL: string;
  SQLITE_DB_PATH: string;
  UPLOADS_DIR: string;
};

export function pm2Ecosystem(env: NodeEnv): string {
  // fork mode + instances:1 is mandatory (SQLite single-writer). This file
  // carries BETTER_AUTH_SECRET, so it is git-ignored by the wizard.
  return `// Generated by \`npm run setup\`. Single instance only (SQLite is single-writer).
// Contains BETTER_AUTH_SECRET — keep it out of version control (git-ignored).
module.exports = {
  apps: [
    {
      name: "seeder",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      cwd: __dirname,
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 2000,
      kill_timeout: 30000,
      listen_timeout: 10000,
      max_memory_restart: "512M",
      time: true,
      error_file: "./logs/seeder.error.log",
      out_file: "./logs/seeder.out.log",
      env: ${JSON.stringify(env, null, 8).replace(/\n}$/, "\n      }")},
    },
  ],
};
`;
}

export function systemdUnit(env: NodeEnv & { root: string }): string {
  // Reads secrets from the git-ignored .env via EnvironmentFile so they aren't
  // duplicated here. Set User= to the account that should own the process.
  return `[Unit]
Description=Seeder (Next.js node server)
After=network.target

[Service]
Type=simple
WorkingDirectory=${env.root}
EnvironmentFile=${env.root}/.env
Environment=NODE_ENV=production
Environment=PORT=${env.PORT}
Environment=HOSTNAME=127.0.0.1
# User=seeder
ExecStart=/usr/bin/env node node_modules/next/dist/bin/next start
Restart=on-failure
RestartSec=2
# Next drains in-flight requests on SIGINT (10–30s); give it room.
KillSignal=SIGINT
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
`;
}

export function dockerfile(): string {
  return `# Generated by \`npm run setup\`. Single container only (SQLite single-writer).
FROM node:22-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ENV RUNTIME=node
RUN npm run build:node

FROM node:22-slim AS run
WORKDIR /app
ENV NODE_ENV=production RUNTIME=node PORT=3000 HOSTNAME=0.0.0.0
COPY --from=build /app ./
EXPOSE 3000
# Apply pending migrations to the mounted SQLite volume, then start.
CMD ["sh", "-c", "npm run db:migrate:node && npm run start:node"]
`;
}

export function dockerCompose(env: NodeEnv): string {
  // Secrets come from the git-ignored .env; container paths point at the named
  // volume so the DB + uploads survive \`docker rm\`.
  return `# Generated by \`npm run setup\`. Do NOT set replicas > 1 (SQLite single-writer).
services:
  seeder:
    build: .
    env_file: .env
    environment:
      - RUNTIME=node
      - SQLITE_DB_PATH=/data/seeder.db
      - UPLOADS_DIR=/data/uploads
    ports:
      - "127.0.0.1:${env.PORT}:3000"
    volumes:
      - seeder-data:/data
    restart: unless-stopped
    stop_grace_period: 30s

volumes:
  # Load-bearing: without this volume the SQLite DB + uploads are lost on rm.
  seeder-data:
`;
}

export function caddyfile(appUrl: string, port: string): string {
  let host = "your-domain.example";
  try {
    host = new URL(appUrl).host;
  } catch {
    // keep placeholder
  }
  return `# Generated by \`npm run setup\`. Caddy auto-provisions Let's Encrypt TLS.
# \`next start\` serves plain HTTP; this terminates TLS and forwards X-Forwarded-*.
${host} {
\treverse_proxy 127.0.0.1:${port}
}
`;
}

export function runbook(env: NodeEnv & { pmChoice: string }): string {
  const startSection =
    env.pmChoice === "1"
      ? "pm2 start ecosystem.config.cjs && pm2 save\npm2 startup   # prints a sudo command to enable boot persistence"
      : env.pmChoice === "2"
        ? "sudo cp seeder.service /etc/systemd/system/\nsudo systemctl enable --now seeder"
        : env.pmChoice === "3"
          ? "docker compose up -d --build"
          : "npm run start:node";

  return `# Seeder — production (node) runbook

This instance runs as a standalone Node server (\`next start\`) backed by a local
SQLite file and local-disk uploads. No Cloudflare dependency.

## Config
- App URL: ${env.BETTER_AUTH_URL}
- Database: \`${env.SQLITE_DB_PATH}\`  (SQLite, single writer)
- Uploads: \`${env.UPLOADS_DIR}\`
- Port: ${env.PORT} (bind 127.0.0.1; the reverse proxy faces the internet)
- Secrets live in \`.env\` (git-ignored). Never commit it.

## Lifecycle
\`\`\`bash
npm run build:node        # rebuild after pulling changes
npm run db:migrate:node   # apply new migrations (safe to re-run; idempotent)
${startSection}
\`\`\`

## Reverse proxy / TLS
\`next start\` serves plain HTTP. Put Caddy (generated \`Caddyfile\`) or Nginx in
front for HTTPS. For Nginx, also set \`proxy_set_header X-Accel-Buffering no;\` so
streamed responses (image downloads) aren't buffered.

## Operations
- **Single instance only.** SQLite is a single writer — never run PM2 cluster
  mode, multiple systemd copies, or \`replicas > 1\`.
- **Graceful shutdown.** The server drains in-flight requests on SIGINT/SIGTERM
  (10–30s); the artifacts allow for that timeout.
- **Backups.** Stop writes or use a consistent copy: \`cp ${env.SQLITE_DB_PATH}\`
  plus the \`${env.UPLOADS_DIR}\` directory. For continuous backup, consider
  Litestream.

## First run
Open ${env.BETTER_AUTH_URL}/sign-in and create the owner account
(${env.OWNER_EMAIL}). Public sign-up closes once the owner exists; invite the
rest of the team from the Invites page.
`;
}
